### ISSUE TITLE
can't create project in vs2022-preview version 17.0.0prview 2.1

### ISSUE THREAD

**Issue by lwqwag** [egvijayanand/dotnet-maui-templates#11]
![1627875262(1)](https://user-images.githubusercontent.com/29883542/127801116-b1bfb76f-700c-4c90-ab76-d8bf95169679.jpg)

dotnet version=6.0.100-preview.6.21355.2

**Comment by egvijayanand** [comment]
Hi @lwqwag,

Analyzing this issue will get back with an update.

Would like to know more about the way the extension is installed, from VS IDE or from VS Marketplace?

Regards,
Vijay Anand E G

**Comment by lwqwag** [comment]
> Hi @lwqwag,
> 
> Analyzing this issue will get back with an update.
> 
> Would like to know more about the way the extension is installed, from VS IDE or from VS Marketplace?
> 
> Regards,
> Vijay Anand E G

I removed the extension and installed it again,it works nice now .
Thanks for reply anyway.

**Comment by egvijayanand** [comment]
Hi @lwqwag,

Glad to know it works. Keep exploring.

To know the root cause, would like to know whether you've upgraded from the initial 1.0.0.0 version to the latest 1.0.0.1 version or started from the latest one.

Regards,
Vijay Anand E G

**Comment by lwqwag** [comment]
Yes ,it is latest version 1.0.0.1 now.
