### ISSUE TITLE
Can we get template for MAUI Class library 

### ISSUE THREAD

**Issue by PaulAnderson02** [egvijayanand/dotnet-maui-templates#16]
Can we get template for creeating a MAUI Class library.

**Comment by egvijayanand** [comment]
Hi @PaulAnderson02,

Since the steps for creating a .NET MAUI class library (and how to manage dependencies) is not yet emerged, this request can't be entertained for now.

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Hi @PaulAnderson02,

The workaround would be to use a class library template configured as a .NET MAUI library.

If you're working with .NET CLI, then `dotnet new classlib` would create a new library project (or) if Visual Studio, create a new Class Library project.

**Manual Steps:**

In the C# project file, replace the `<TargetFramework>` element with the following:

```xml
<TargetFrameworks>net6.0-ios;net6.0-android;net6.0-maccatalyst;net6.0-windows</TargetFrameworks>
```
And then add the .NET MAUI element:

```xml
<UseMaui>true</UseMaui>
```
Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Hi @PaulAnderson02,

Glab to inform you that your request for .NET MAUI Class Library project template has been accepted.

Will release them by today.

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Hi @PaulAnderson02,

VS extension and NuGet package have been updated with the **.NET MAUI Class Library** project template and are released to the respective distribution channels.

Update them for the changes to reflect.

For more details, refer to my [blog post](https://egvijayanand.in/2021/07/18/net-maui-templates-for-visual-studio-2022/) and GitHub readme.

**Comment by PaulAnderson02** [comment]
@egvijayanand  Awesome
