### ISSUE TITLE
ARM64 support for the extension

### ISSUE THREAD

**Issue by MagicAndre1981** [egvijayanand/dotnet-maui-templates#253]
Currently you only [support AMD64](https://github.com/egvijayanand/dotnet-maui-templates/blob/9db0bddcb82a8b9699bcc5207348b3d3f543cf3e/src/Extensions/MauiTemplates/MauiTemplates/source.extension.vsixmanifest#L23). 

Any reason why you exclude arm64? People who bought one of the Qualcomm Snapdragon X Elite laptops may want to use the [arm64 version of VS2022](https://learn.microsoft.com/en-us/visualstudio/install/visual-studio-on-arm-devices?view=vs-2022#get-started-with-arm64-visual-studio) so you should also give them your extension.

**Comment by egvijayanand** [comment]
@MagicAndre1981 It's on my radar, will check on the feasibility of adding the requested feature.

Meanwhile, if you've found these extensions helpful in getting your work done quickly, please think about [sponsoring the project](https://github.com/sponsors/egvijayanand). Your support means a lot!

**Comment by MagicAndre1981** [comment]
MAUI works since [VS2022 17.6](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.6) for ARM64:

> We now support the .NET Multi-platform App UI (MAUI) workload on Arm64 Visual Studio.

```
<InstallationTarget Id="Microsoft.VisualStudio.Community"
                    Version="[17.6, 18.0)">
    <ProductArchitecture>arm64</ProductArchitecture>
</InstallationTarget>
```

**Comment by egvijayanand** [comment]
This feature is now part of the below release. 

* .NET MAUI Project and Item Templates - [v5.12.0.0](https://marketplace.visualstudio.com/items?itemName=egvijayanand.maui-templates)

Update now. Happy coding!
