### ISSUE TITLE
Compile error with RC1

### ISSUE THREAD

**Issue by 420tech** [egvijayanand/dotnet-maui-templates#47]
Need instructions on use. Compile errors with Microsoft.Graphics.Win2D and Microsoft.WindowsAppSDK not upgrading the nuget. If you manually fix it in the csproj, 3 other compile errors occur.

**Comment by egvijayanand** [comment]
Hi Tim Belvin @420tech,

For time being follow the instructions as laid out in this [Migration Guide to RC1](https://github.com/dotnet/maui/wiki/Migrating-to-RC1).

In general, you need to remove the `ItemGroup` node with the Windows platform target condition for referencing the Windows App SDK NuGet packages.

An updated version of the .NET MAUI Templates NuGet package and VSIX extension to support RC1 is under modification and will be released today.

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Hi @420tech,

Thank you for your time in reporting this issue.

Now, RC1 supported [NuGet package](https://www.nuget.org/packages/VijayAnand.MauiTemplates/), and [VS extension](https://marketplace.visualstudio.com/items?itemName=egvijayanand.maui-templates) is now made available in the respective channels. Kindly update to the latest version. 

Happy coding. Stay connected with my [**Developer Thoughts**](https://egvijayanand.in/) blog for working with these templates.

Note: As a new feature, App theming support added to the .NET MAUI Blazor Hybrid App project

Regards,
Vijay Anand E G
