### ISSUE TITLE
Add option to include Microsoft.Toolkit.Mvvm

### ISSUE THREAD

**Issue by roughiain** [egvijayanand/dotnet-maui-templates#52]
Improvement: Add option to include Microsoft.Toolkit.Mvvm

**Comment by egvijayanand** [comment]
I hope you're referring to the latest talk of the town: CommunityToolkit.Mvvm NuGet package.

If so, yes it's in my radar.

Have even published an article on this.

https://egvijayanand.in/2022/04/22/mvvm-made-easy/

**Comment by roughiain** [comment]
> I hope you're referring to the latest talk of the town: CommunityToolkit.Mvvm NuGet package.
> 
> If so, yes it's in my radar.
> 
> Have even published an article on this.
> 
> https://egvijayanand.in/2022/04/22/mvvm-made-easy/

Yes, the CommunityToolkit.Mvvm,

**Comment by egvijayanand** [comment]
Coming soon.

**Comment by egvijayanand** [comment]
Hi @roughiain,

Thanks for taking your time in providing this feedback.

I'm glad to inform you that this feature is now incorporated in the latest release of the templates pack (both [NuGet](https://www.nuget.org/packages/VijayAnand.MauiTemplates/1.4.0) and [VSIX](https://marketplace.visualstudio.com/items?itemName=egvijayanand.maui-templates)).

This is controlled by the parameter named `-imt` or `--include-mvvm-toolkit` and set its value to yes (case insensitive).

Or if you prefer the UI, it's another simple checkbox option to include the `Microsoft MVVM Toolkit` while creating the project itself.

Happy coding.

Regards,
Vijay Anand E G
