### ISSUE TITLE
Installation on VS 2022 failed

### ISSUE THREAD

**Issue by saigkill** [egvijayanand/dotnet-maui-templates#77]
Today i tried to install your VS Extension from Marketplace. Sadly i'm got:

> 20.08.2022 20:30:49 - Microsoft VSIX Installer
20.08.2022 20:30:49 - -------------------------------------------
20.08.2022 20:30:49 - vsixinstaller.exe version:
20.08.2022 20:30:49 - 17.2.2197
20.08.2022 20:30:49 - -------------------------------------------
20.08.2022 20:30:49 - Command line parameters:
20.08.2022 20:30:49 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Admin\Downloads\VijayAnand.MauiTemplates.vsix
20.08.2022 20:30:49 - -------------------------------------------
20.08.2022 20:30:49 - Microsoft VSIX Installer
20.08.2022 20:30:49 - -------------------------------------------
20.08.2022 20:30:50 - Initializing Install...
20.08.2022 20:30:50 - Erweiterungsdetails...
20.08.2022 20:30:50 - 	Identifier         : MauiTemplates.20dca96a-7311-401f-84ed-980478fb319b
20.08.2022 20:30:50 - 	Name               : .NET MAUI Project and Item Templates
20.08.2022 20:30:50 - 	Author             : Vijay Anand E G
20.08.2022 20:30:50 - 	Version            : 1.7.6.3
20.08.2022 20:30:50 - 	Description        : .NET MAUI Project, Item Templates, and Code Snippets for Visual Studio 2022 (.NET MAUI GA and Service Releases).
20.08.2022 20:30:50 - 	Locale             : en-US
20.08.2022 20:30:50 - 	MoreInfoURL        : https://egvijayanand.in/2022/04/20/all-in-one-dotnet-maui-app-project-template-what-is-new/
20.08.2022 20:30:50 - 	InstalledByMSI     : False
20.08.2022 20:30:50 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
20.08.2022 20:30:50 - 
20.08.2022 20:30:50 - 	SignatureState     : Unsigned
20.08.2022 20:30:50 - 	Unterstützte Produkte : 
20.08.2022 20:30:50 - 		Microsoft.VisualStudio.Community
20.08.2022 20:30:50 - 			Version : [17.3,18.0)
20.08.2022 20:30:50 - 			ProductArchitecture : amd64
20.08.2022 20:30:50 - 		Microsoft.VisualStudio.Pro
20.08.2022 20:30:50 - 			Version : [17.3,18.0)
20.08.2022 20:30:50 - 			ProductArchitecture : amd64
20.08.2022 20:30:50 - 		Microsoft.VisualStudio.Enterprise
20.08.2022 20:30:50 - 			Version : [17.3,18.0)
20.08.2022 20:30:50 - 			ProductArchitecture : amd64
20.08.2022 20:30:50 - 
20.08.2022 20:30:50 - 	Verweise           : 
20.08.2022 20:30:50 - 	Voraussetzungen    : 
20.08.2022 20:30:50 - 		-------------------------------------------------------
20.08.2022 20:30:50 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
20.08.2022 20:30:50 - 		Name         : Visual Studio core editor
20.08.2022 20:30:50 - 		Version      : [17.3,)
20.08.2022 20:30:50 - 
20.08.2022 20:30:50 - 		-------------------------------------------------------
20.08.2022 20:30:50 - 		Identifier   : Microsoft.VisualStudio.ComponentGroup.Maui.All
20.08.2022 20:30:50 - 		Name         : .NET MAUI
20.08.2022 20:30:50 - 		Version      : [17.3.32505.122,18.0)
20.08.2022 20:30:50 - 
20.08.2022 20:30:50 - Signaturdetails...
20.08.2022 20:30:50 - 	Extension is not signed.
20.08.2022 20:30:50 - 
20.08.2022 20:30:50 - Er wird nach passenden Produkten gesucht...
20.08.2022 20:30:50 - Installiertes Produkt gefunden - Globaler Pfad
20.08.2022 20:30:50 - Installiertes Produkt gefunden - Visual Studio Enterprise 2022 LTSC 17.2
20.08.2022 20:30:50 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

Do you know, how to fix it?

**Comment by egvijayanand** [comment]
Hello @saigkill,

Thanks for your interest in installing my extension and in turn trying out .NET MAUI.

From the log you've shared, it seems you're trying to install this extension on **VS2022 LTSC**.

Hopefully, you've selected and installed the .NET MAUI optional workload component while installing VS IDE as it's **VS2022 17.2**.

> 20.08.2022 20:30:50 - Installiertes Produkt gefunden - Visual Studio Enterprise 2022 LTSC 17.2
> 20.08.2022 20:30:50 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.

While building this extension, haven't come across such a **product SKU (LTSC)** and it only listed the below-mentioned editions (Community, Pro, and Enterprise).

> 20.08.2022 20:30:50 - Unterstützte Produkte :
> 20.08.2022 20:30:50 - Microsoft.VisualStudio.Community
> 20.08.2022 20:30:50 - Version : [17.3,18.0)
> 20.08.2022 20:30:50 - ProductArchitecture : amd64
> 20.08.2022 20:30:50 - Microsoft.VisualStudio.Pro
> 20.08.2022 20:30:50 - Version : [17.3,18.0)
> 20.08.2022 20:30:50 - ProductArchitecture : amd64
> 20.08.2022 20:30:50 - Microsoft.VisualStudio.Enterprise
> 20.08.2022 20:30:50 - Version : [17.3,18.0)
> 20.08.2022 20:30:50 - ProductArchitecture : amd64

Need to check with the official VS extensions team reg. this and request your patience in the interim. I'm happy to include this product SKU too, hopefully it's supported by VS2022 extensions.

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
And from the supported version details, .NET MAUI is available on the **Stable channel VS2022 17.3** or **Preview channel 17.4 Preview 1.0** as of this date. _This extension supports even the 17.3 Preview releases, any version starting from 17.3 onwards._

Request to also check whether **.NET Multi-platform App UI development** optional component (refer below screenshot for details) is installed as part of Visual Studio 2022 as it's a prerequisite for installing my extension (without which installing this extension would be meaningless).

![image](https://user-images.githubusercontent.com/81947404/185803940-1958bb93-d426-4682-a2f6-0548e9d13b23.png)

I hope LTSC is a baselined version channel where one would get support fixes for a longer duration when compared to other minor versions but would fall under any of the three product SKUs. Anyway, I would get this clarified with the official product team.

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Even-numbered minor releases are LTSC and are supported for a longer duration (18 months).

https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-servicing#long-term-servicing-channel-ltsc-support

But to develop .NET MAUI App, one would require, as of this writing, VS2022 17.3 or higher (17.3 on the Stable channel or 17.4 on the Preview channel).

https://docs.microsoft.com/en-us/dotnet/maui/get-started/first-app?pivots=devices-windows#get-started-with-visual-studio-2022-173

Unfortunately, this optional component is not yet on any of the Stable LTSC for now (would be part of 17.4 when it reaches Stable).

If you've no other option, request to check for breaking changes and consider upgrading to **17.3 Stable** to develop .NET MAUI Apps by installing the optional component and my extension too.

Happy coding!!!

Regards,
Vijay Anand E G
