### ISSUE TITLE
How can I use Hybrid in Shell Design Pattern?

### ISSUE THREAD

**Issue by pccai** [egvijayanand/dotnet-maui-templates#93]
Like every shell page has a BlazorWebView and received some args(h5 url).
tks.

**Comment by egvijayanand** [comment]
I don't understand your question in full.

But from template perspective, it's not possible to mix and match design pattern.

But from framework perspective, BlazorWebView is just another control inherited from View so it can be made to occupy however you want like whole page or part of the page contained a layout.

Parameters can be passed to a Razor component and lifecycle method available to handle them as well.

Check this multi targeted Blazor solution which implements Shell in a Hybrid scenario.

https://github.com/egvijayanand/WeeklyXamarinBlazor

**Comment by pccai** [comment]
Nice!
I will use SPA which build React in BlazorWebView for blank page.

![image](https://user-images.githubusercontent.com/2232794/203918833-233e9480-f79b-4e9a-bbbf-b83f354dd6a6.png)
